### ISSUE TITLE
Allow user to choose screenshotFolder

### ISSUE THREAD

**Issue by ChrisSmartNews** [codeceptjs/codeceptjs-resemblehelper#109]
Currently the `screenshotFolder` is defaulted to the codeceptjs `output` folder no matter what you set in the `ResembleHelper` config.

I would like to set the screenshot folder because:

I currently run both Webkit and Chromium tests and taking screenshots differ between them by a little. I want to have separate base images for webkit and chromium. 

I want to have the base images for the same test in two different folders - webkit and chromium. But the inability to change the screenshotFolder means that I cannot have two images of the same file name. The workaround is to just name the base images `chromium-filename` and `webkit-filename` but I feel like this is messier.

**Comment by puneet0191** [comment]
I get your point, whats a solution you can propose around this? @ChrisSmartNews

**Comment by ChrisSmartNews** [comment]
Hello, thanks for replying! I was thinking the obvious solution which is to make `screenshotFolder` configurable. The user can make it the same as their output dir if they want.  I only started looking at `resemblehelper` yesterday so let me know if I'm missing something here 😄  Just not too sure why the screenshot folder was designed here to be un-configurable.

**Comment by sharath2106** [comment]
@ChrisSmartNews We'll try to add this in our next release.
