### ISSUE TITLE
Output Settings ignoreAreasColoredWith applied to wrong image

### ISSUE THREAD

**Issue by pgoellnitz** [codeceptjs/codeceptjs-resemblehelper#122]
Hi,
I struggled making the output setting `ignoreAreasColoredWith` working. I found that in addition to https://github.com/codeceptjs/codeceptjs-resemblehelper/issues/118 the setting area is not applied to the base image but to the tested one.

I believe the images would need to be reversed here:
https://github.com/codeceptjs/codeceptjs-resemblehelper/blob/52afc96b474ae35d5cfdc8ada18c7cb9ab607b01/index.js#L96

**Comment by sharath2106** [comment]
Thanks for the MR @pgoellnitz. We have released the latest version ([1.9.7](https://www.npmjs.com/package/codeceptjs-resemblehelper)) of the library yesterday. I would ask to check against the latest version and let us know.
