### ISSUE TITLE
node crashes when image comparison difference is larger than the tolerance threshold.

### ISSUE THREAD

**Issue by gtycherry** [codeceptjs/codeceptjs-resemblehelper#69]
Hi There, 

I ran below error when I do visual testing via resemblehelper. Can anyone help to take a look? Thanks a lot.
The helper works well when the difference is under the tolerance indicator, only crashes when the image comparison difference is bigger than the tolerance.
![image](https://user-images.githubusercontent.com/8056464/83485553-debce000-a4d9-11ea-93ad-80356441e972.png)

The project dependencies as below : 

>  "devDependencies": {
    "mocha": "^5.2.0",
    "mocha-multi": "^1.0.1",
    "puppeteer": "^1.15.0"
  },
  "dependencies": {
    "codeceptjs": "^2.6.5",
    "codeceptjs-resemblehelper": "1.9.0",
    "mocha-junit-reporter": "^1.18.0",
    "mochawesome": "^3.1.1"
  }

 

And node version is : 8.11.3 
Also tried with node: 10.20.1, the issue still exists.

![image](https://user-images.githubusercontent.com/8056464/83592520-1cc70c00-a58d-11ea-8640-149fb9b13561.png)

**Comment by puneet0191** [comment]
@gtycherry any specific reason why you use node v8?

**Comment by gtycherry** [comment]
Hi @puneet0191 
I ran into some other issue when I use V10:
![image](https://user-images.githubusercontent.com/8056464/83488402-5f320f80-a4df-11ea-9674-b329df94b956.png)

I ran into above issue even without image comparison. My colleague also have the same V10 codeceptjs issue and V8 resemblehelper issue.

**Comment by puneet0191** [comment]
@gtycherry please try to use codeceptjs 1.9.0, I think you use the latest 1.9.1 which could be having this issue, and the issue with node 10, is because you have some old files in bcrypt, try to do it on a clean node_module folder, https://stackoverflow.com/questions/46384591/node-was-compiled-against-a-different-node-js-version-using-node-module-versio

**Comment by gtycherry** [comment]
Hi @puneet0191 
Thanks for recommendation. But seems I was without luck.
I think you meant resemble helper version should be 1.9.0. I tried both 1.9.1 and 1.9.0 Both didn't work. 
For the V10 issue, per your tips, the original error disappeared, and all the test ran successfully. But there was a new issue come out when generating test report.
![image](https://user-images.githubusercontent.com/8056464/83494142-67db1380-a4e8-11ea-83e6-c5fe7c213433.png)

**Comment by puneet0191** [comment]
@gtycherry I am not sure how this is related to the helper, please check if you get this error without using the helper?

**Comment by gtycherry** [comment]
@puneet0191  I think without the helper ,codecepjs itself can't do image comparison. 
I refered to the doc here https://codecept.io/visual/#using-resemble-helper

**Comment by puneet0191** [comment]
@gtycherry I am just trying to understand, if the problem is because of helper or something else in generating the report.

**Comment by gtycherry** [comment]
@puneet0191  
seems i confused you here, the reporter issue is for V10 testing run(this is to reply to you about why i must use V8). But my original priority one issue is nodejs crashes when visual testing found difference bigger than the specified threshold. 
2 different problem, maybe we can ignore the V10 issue at the moment. But only focus on the crash issue.

**Comment by puneet0191** [comment]
@gtycherry are you still able to reproduce this? I haven't encountered any reports, please feeel free to reopen in case this still is a problem for you, thanks a lot for reporting.
