### ISSUE TITLE
saveScreenshot into seeVisualDiff/seeVisualDiffForElement

### ISSUE THREAD

**Issue by puneet0191** [codeceptjs/codeceptjs-resemblehelper#7]
use the `saveScreenshot` method within the seeVisualDiff/seeVisualDiffForElement methods and make them perform complete action

**Comment by srbhss** [comment]
Feature('Screen comparison with Resemble Js test');

Scenario('Compare web page with visual test', async (I) => {
    I.amOnPage("url/");
    I.saveScreenshot("Codecept_IO_Screenshot_Image.png");
    I.seeVisualDiff("Codecept_IO_Screenshot_Image.png", {prepareBaseImage: 'false', tolerance: 3});
});
