### ISSUE TITLE
Download base images doesn't work only with prepareBaseImage global

### ISSUE THREAD

**Issue by caragpe** [codeceptjs/codeceptjs-resemblehelper#78]
When using method `_assertVisualDiff` , we are only downloading the base image if the `options` param explicitly includes the option `{prepareBaseImage: false}`. Otherwise, it will omit downloading the base file, even if the helper configuration includes the `prepareBaseImage` option.

My suggestion is to check the config option for `prepareBaseImage` when this option is missing in the `_assertVisualDiff` method:

```
const prepareBaseImage = options.prepareBaseImage !== undefined
      ? options.prepareBaseImage
      : (this.prepareBaseImage === true)
if (awsC !== undefined && prepareBaseImage === false) {
      await this._download(awsC.accessKeyId, awsC.secretAccessKey, awsC.region, awsC.bucketName, baseImage);
}
```

Check [PR #79 here](https://github.com/codeceptjs/codeceptjs-resemblehelper/pull/79)

**Comment by puneet0191** [comment]
thanks @caragpe I will review and approve! thank you for your contribution.

**Comment by puneet0191** [comment]
@caragpe I am closing this issue as it has been released, please feel free to reopen if you still have this problem
