### ISSUE TITLE
Global prepareBaseImage not working

### ISSUE THREAD

**Issue by fsblemos** [codeceptjs/codeceptjs-resemblehelper#88]
Hi!

After [this change](https://github.com/codeceptjs/codeceptjs-resemblehelper/pull/79), the global `prepareBaseImage` is not generating the base images. It's only working when passing to `seeVisualDiff`.

I'm opening a PR to fix it, can you take a look?

Thanks for you work

**Comment by puneet0191** [comment]
thanks a lot for reporting, I will look at the PR's

**Comment by puneet0191** [comment]
@fsblemos could you help test https://github.com/codeceptjs/codeceptjs-resemblehelper/pull/90/ has some refactoring and also fixes the issue you reported.

**Comment by fsblemos** [comment]
Thank you @puneet0191! #90 looks great and solves this issue! I can close #89 then

**Comment by puneet0191** [comment]
thanks a lot for checking, I really appreciate it.

**Comment by puneet0191** [comment]
Releasing with the fix thanks
