### ISSUE TITLE
Mochawesome context gets absolute paths instead of relative to Images

### ISSUE THREAD

**Issue by jpmschuler** [codeceptjs/codeceptjs-resemblehelper#95]
In order for the mocha awesome HTML report to be more helpful it would be nice if `_addMochaContext` https://github.com/codeceptjs/codeceptjs-resemblehelper/blob/master/index.js#L168 would supply relative paths to the images.As we (like most) probably run CI/CD the build artefacts are not viewed on the same system they are created, thus they won't be shown:
![Bildschirmfoto 2021-09-10 um 01 05 55](https://user-images.githubusercontent.com/12411176/132773881-3c7ac5d0-ff2c-4be9-9a57-7fe1e23f318a.png)

Check the following Mochawesome report.json snippet (the report.html code is a mess, but looks similar):
```json
   "context": "[
   \n  \"Base Image\",\n  \"/builds/project-management/myproject/tests/output/base/RCA-desktop.png\",
   \n  \"ScreenShot Image\",\n  \"/builds/project-management/myproject/tests/output/RCA-desktop.png\",
   \n  \"Diff Image\",\n  \"/builds/project-management/myproject/tests/output/diff/Diff_RCA-desktop.png\",
   \n  \"Screenshot_e693b747-f9a3-481a-8060-8ef6b6df1005.failed.png\"\n]",
   ```
The first 3 are generated by `codecept-resemblehelper` the last by ScreenShotOnFailure plugin. Thus it seems plausible that relative paths work.

(Don't have a fix, nor a MWE, nor a test yet, just found that as GitLab artefact view was broken)

**Comment by puneet0191** [comment]
Thanks a lot, fixed with https://github.com/codeceptjs/codeceptjs-resemblehelper/releases/tag/v1.9.5
